# pipeline for aws : not need
#image: python:3.5.1

#pipelines:
#  branches:
#    master:
#      - step:
#          script:
#            - git archive -o carrental.zip HEAD
#            - pip install boto3==1.3.0 # required for s3_upload.py
#            - python s3_upload.py source-drop carrental.zip carrental.zip # run the deployment script

image: ruby:2.4.0

pipelines:
  default:
    - step:
        script:
          - echo "building with buildpacks"
          - apt-get update -qy
          #- apt-get install -y ruby-dev
          - gem install dpl
          #- dpl --provider=deis --app=madcap-lakeside --controller=deis.35.198.252.127.nip.io --username=$DEIS_USERNAME --password=$DEIS_PASSWORD --cli_version=v2.16.0
          - git push ssh://$DEIS_BUILDER/$APP_NAME.git HEAD

definitions:
  caches:
    bundler: ./vendor