apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # name: {{ template "fullname" . }}
  name: {{ template "trackableappname" . }}
  labels:
    #draft: {{ default "draft-app" .Values.draft }}
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        #draft: {{ default "draft-app" .Values.draft }}
        #app: {{ template "fullname" . }}
    spec:
      # containers:
      # - name: {{ .Chart.Name }}
      #   image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      #   imagePullPolicy: {{ .Values.image.pullPolicy }}
      #   ports:
      #   - containerPort: {{ .Values.service.internalPort }}
      #   livenessProbe:
      #     httpGet:
      #       path: /
      #       port: {{ .Values.service.internalPort }}
      #   readinessProbe:
      #     httpGet:
      #       path: /
      #       port: {{ .Values.service.internalPort }}
      #   resources:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DATABASE_URL
          value: {{ .Values.application.database_url | quote }}
        - name: APP_KEY
          value: {{ .Values.env.APP_KEY | quote }}
        - name: DB_HOST
          value: {{ .Values.env.DB_HOST | quote }}
        - name: DB_DATABASE
          value: {{ .Values.env.DB_DATABASE | quote }}
        - name: DB_USERNAME
          value: {{ .Values.env.DB_USERNAME | quote }}
        - name: DB_PASSWORD
          value: {{ .Values.env.DB_PASSWORD | quote }}
        ports:
        - name: "{{ .Values.service.name }}"
          containerPort: {{ .Values.service.internalPort }}
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.service.internalPort }}
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 15
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.service.internalPort }}
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 3
        resources:
{{ toYaml .Values.resources | indent 12 }}
